model = "jsc-three-linear-layers"
dataset = "jsc"
data_loader = "default"
# data_module = "default"
# dataset_dir = "/home/xinyi/mase_xinyi/mase_data/jsc"

[training]
model = "mg.model"
model_info = "self.model_info"
data_module = "default"
dataset_info = "jsc"
task = "cls"
optimizer = "adam"
weight_decay = 0.001


max_epochs = 1
batch_size = 128
learning_rate = 1e-2
accelerator = "cpu"
project = "jsc-three-linear-layers"
seed = 42
log_every_n_steps = 5
load_name = "/home/xinyi/mase_xinyi/mase_output/jsc-three-linear-layers_classification_jsc_2024-02-08/software/training_ckpts/best.ckpt"
load_type = "pl"

[search.search_space]
name = "graph/quantize/channel_size_modifier"

#[search.search_space.setup]
#by = 'name'

[search.search_space.seed.default.config]
# the only choice "NA" is used to indicate that layers are not quantized by default
name = ["NA"]
channel_multiplier = [1]

[search.search_space.seed.seq_blocks_2.config]
name = ["output_only"]
channel_multiplier = [1, 2]
parent_block_name = ["seq_blocks_1"]

[search.search_space.seed.seq_blocks_3.config]
name = ["both"]
parent_block_name = ["seq_blocks_2"]
channel_multiplier = [1, 2, 3]

[search.search_space.seed.seq_blocks_4.config]
name = ["input_only"]
parent_block_name = ["seq_blocks_3"]
channel_multiplier = [2, 4, 6]


[search.strategy]
name = "optuna"
eval_mode = true

[search.strategy.sw_runner.basic_evaluation]
data_loader = "val_dataloader"
num_samples = 512

[search.strategy.hw_runner.average_bitwidth]
compare_to = 32 # compare to FP32

[search.strategy.setup]
n_jobs = 1
n_trials = 20
timeout = 20000
sampler = "tpe"
sum_scaled_metrics = true # single objective
direction = "maximize"

[search.strategy.metrics]
accuracy.scale = 1.0
accuracy.direction = "maximize"